from pathlib import Path

level_names = {
"1-0.dem": "Overworld Start",
"1-1.dem": "Lachrymose Head",
"1-2.dem": "Southjaunt",
"1-3.dem": "Infant's Break",
"1-4.dem": "Comely Hearth",
"1-5.dem": "Little Fire",
"1-6.dem": "Eastreach",
"1-7.dem": "Bay's Neck",
"1-8.dem": "Burning Wharf",
"1-9.dem": "Happy Pool",
"1-10.dem": "Maiden's Walk",
"1-11.dem": "Fiery Jut",
"1-12.dem": "Merchant's Elegy",
"1-13.dem": "Seafinger",
"1-14.dem": "The Clover",
"1-15.dem": "Inlet Shore",
"1-16.dem": "The Anchorage",
"1-final.dem": "Overworld Sausage 1",

"2-1.dem": "Emerson Jetty",
"2-2.dem": "Sad Farm",
"2-3.dem": "Cove",
"2-4.dem": "The Great Tower",
"2-5.dem": "The Paddock",
"2-6.dem": "Beautiful Horizon",
"2-7.dem": "Barrow Set",
"2-8.dem": "Rough Field",
"2-9.dem": "Fallow Earth",
"2-10.dem": "Twisty Farm",
"2-final.dem": "Overworld Sausage 2",

"3-1.dem": "Cold Jag",
"3-2.dem": "Cold Finger",
"3-3.dem": "Cold Escarpment",
"3-4.dem": "Cold Frustration",
"3-5.dem": "Cold Trail",
"3-6.dem": "Cold Cliff",
"3-7.dem": "Cold Pit",
"3-8.dem": "Cold Plateau",
"3-9.dem": "Cold Head",
"3-10.dem": "Cold Ladder",
"3-11.dem": "Cold Sausage",
"3-12.dem": "Cold Terrace",
"3-13.dem": "Cold Horizon",
"3-14.dem": "Cold Gate",
"3-final.dem": "Overworld Sausage 3",

"4-1.dem": "Wretch's Retreat",
"4-2.dem": "Toad's Folly",
"4-3.dem": "Sludge Coast",
"4-4.dem": "Foul Fen",
"4-5.dem": "Crunchy Leaves",
"4-6.dem": "Gator Paddock",
"4-final.dem": "Overworld Sausage 4",

"5-1.dem": "The Gorge",
"5-2.dem": "Widow's Finger",
"5-3.dem": "Skeleton",
"5-4.dem": "Slope View",
"5-5.dem": "Land's End",
"5-6.dem": "Crater",
"5-7.dem": "Pressure Points",
"5-8.dem": "Open Baths",
"5-9.dem": "Drumlin",
"5-10.dem": "Tarry Ridge",
"5-11.dem": "Rough View",
"5-12.dem": "Baby Rock",

"5-final.dem": "Dead End Setup",
"6-1.dem": "Dead End",
"6-1.5.dem": "Sea Dragon Setup",
"6-2.dem": "Sea Dragon",
"6-2.5.dem": "Folklore Setup",
"6-3.dem": "Folklore",
"6-3.5.dem": "The Decay Setup",
"6-4.dem": "The Decay",
"6-4.5.dem": "The Splitting Bough Setup",
"6-5.dem": "The Splitting Bough",
"6-5.5.dem": "Captive Hydra Setup",
"6-6.dem": "Captive Hydra",
"6-6.5.dem": "Rattlesnakes Setup",
"6-7.dem": "Rattlesnakes",
"6-7.5.dem": "Sty Setup",
"6-8.dem": "Sty",
"6-8.5.dem": "Split Face Setup",
"6-9.dem": "Split Face",
"6-9.5.dem": "Four-faced Liar Setup",
"6-10.dem": "Four-faced Liar",
"6-10.5.dem": "Suspension Bridge Setup",
"6-11.dem": "Suspension Bridge",
"6-11.5.dem": "Curious Dragons Setup",
"6-12.dem": "Curious Dragons",
"6-12.5.dem": "Ancient Dam Setup",
"6-13.dem": "Ancient Dam",
"6-13.5.dem": "Apex Setup",
"6-14.dem": "Apex",
"6-14.5.dem": "The Stone Tree Setup",
"6-15.dem": "The Stone Tree",
"6-15.5.dem": "The Backbone Setup",
"6-16.dem": "The Backbone",
"6-16.5.dem": "Baby Swan Setup",
"6-17.dem": "Baby Swan",
"6-17.5.dem": "Shy Dragon Setup",
"6-18.dem": "Shy Dragon",
"6-18.5.dem": "Lovers' Sadness Setup",
"6-19.dem": "Lovers' Sadness",
"6-19.5.dem": "Dragonclaw Setup",
"6-20.dem": "Dragonclaw",
"6-20.5.dem": "Obscene Gesture Setup",
"6-21.dem": "Obscene Gesture",
"6-21.5.dem": "The Nursery Setup",
"6-22.dem": "The Nursery",
"6-22.5.dem": "Canal Setup",
"6-23.dem": "Canal",
"6-23.5.dem": "Mommy Swan Setup",
"6-24.dem": "Mommy Swan",
"6-24.5.dem": "Loft of the Spirit Setup",
"6-25.dem": "Loft of the Spirit",
"6-25.5.dem": "Wobblecliff Setup",
"6-26.dem": "Wobblecliff",
"6-26.5.dem": "Plateau Ferry Setup",
"6-27.dem": "Plateau Ferry",
"6-27.5.dem": "God Pillar Setup",
"6-28.dem": "God Pillar",
"6-final.dem": "Final cleanup",
"all.dem": "All",
}

demos = Path('.').glob('*.dem')
demo_stats = []
for demo in demos:
    with demo.open('r') as f:
        moves = f.read().count('\n')
        name = level_names[demo.name]
        if 'Setup' in name:
            continue
        demo_stats.append((moves, name))
demo_stats.sort()
for stat in demo_stats:
    print(f'{stat[1]}: {stat[0]} moves')
